export const enquiryCopy = {
  zh: {
    role: '您的角色 / 咨询主题',
    roles: { farmer: '农户 / 资产所有者', investor: '投资者 / 金融合作伙伴', warehouse: '仓储 / 贸易合作伙伴', other: '其他' },
    optional: '选填', send: '发送咨询', pending: '正在等待接收确认…',
    accepted: '邮件服务商已接收您的咨询，但尚未确认已送达收件箱。',
    failed: '无法确认咨询是否已被接收。请保留原信息重试，或改用电子邮件。请避免通过两种方式重复发送同一咨询。',
    unavailable: '暂不支持在线提交。请在下方准备邮件草稿，再通过您的邮件应用发送。',
    invalid: '请检查标出的字段。', fieldError: '请检查此字段的内容和长度。',
    consent: '我同意 Commodity Chain Ltd. 使用这些信息回复我的咨询。',
    privacy: '这些信息将用于回复您的咨询。启用在线提交时，消息将转交邮件服务商并发送至 info@commochain.ltd。不接受附件。请勿包含保密信息或敏感个人信息。如有数据相关问题，请联系 info@commochain.ltd。',
    fallbackPrivacy: '准备草稿不会通过本网站发送或保存您的信息。您可自行决定是否通过邮件应用发送。',
    emailFallback: '希望通过邮件联系？', retry: '重试发送同一咨询', newEnquiry: '发起新的咨询',
  },
  en: { role:'Your role / enquiry', roles:{farmer:'Farmer / asset owner',investor:'Investor / financial partner',warehouse:'Warehouse / trading partner',other:'Other'}, optional:'optional', send:'Send enquiry', pending:'Requesting acceptance…', accepted:'Your enquiry was accepted by our email provider. Mailbox delivery is not yet confirmed.', failed:'We could not confirm acceptance. Retry with the unchanged details, or use email. Please avoid sending the same enquiry by both routes.', unavailable:'Online submission is not available. Prepare an email draft below, then send it using your email app.', invalid:'Please check the highlighted fields.', fieldError:'Check this field and its length.', consent:'I agree that Commodity Chain Ltd. may use these details to respond to my enquiry.', privacy:'These details are used to respond to your enquiry. When online submission is enabled, the message is passed to our email delivery provider and info@commochain.ltd. No attachments are accepted. Do not include confidential or sensitive personal information. Contact info@commochain.ltd about your data.', fallbackPrivacy:'Preparing a draft does not send or store your details on this website. You choose whether to send it from your email app.', emailFallback:'Prefer email?', retry:'Retry the same enquiry', newEnquiry:'Start another enquiry' },
  ru: { role:'Ваша роль / тема обращения', roles:{farmer:'Фермер / владелец актива',investor:'Инвестор / финансовый партнёр',warehouse:'Склад / торговый партнёр',other:'Другое'}, optional:'необязательно', send:'Отправить обращение', pending:'Ожидаем подтверждения приёма…', accepted:'Почтовый сервис принял ваше обращение. Доставка в почтовый ящик ещё не подтверждена.', failed:'Не удалось подтвердить приём. Повторите попытку с теми же данными или воспользуйтесь почтой. Пожалуйста, не отправляйте одно обращение обоими способами.', unavailable:'Отправка с сайта пока недоступна. Подготовьте черновик ниже, затем отправьте его через почтовую программу.', invalid:'Проверьте выделенные поля.', fieldError:'Проверьте содержимое и длину этого поля.', consent:'Я согласен на использование этих данных Commodity Chain Ltd. для ответа на обращение.', privacy:'Данные используются для ответа на ваше обращение. При включённой отправке с сайта сообщение передаётся почтовому сервису и на info@commochain.ltd. Вложения не принимаются. Не указывайте конфиденциальные или чувствительные персональные сведения. По вопросам ваших данных пишите на info@commochain.ltd.', fallbackPrivacy:'Подготовка черновика не отправляет и не сохраняет ваши данные на этом сайте. Вы сами решаете, отправлять ли письмо через почтовую программу.', emailFallback:'Удобнее по почте?', retry:'Повторить отправку того же обращения', newEnquiry:'Начать новое обращение' },
  kk: { role:'Рөліңіз / өтініш тақырыбы', roles:{farmer:'Фермер / актив иесі',investor:'Инвестор / қаржы серіктесі',warehouse:'Қойма / сауда серіктесі',other:'Басқа'}, optional:'міндетті емес', send:'Өтінішті жіберу', pending:'Қабылдауды растау күтілуде…', accepted:'Пошта қызметі өтінішіңізді қабылдады. Пошта жәшігіне жеткізілгені әлі расталған жоқ.', failed:'Қабылданғанын растау мүмкін болмады. Сол деректермен қайталап көріңіз немесе поштаны пайдаланыңыз. Бір өтінішті екі жолмен қатар жібермеңіз.', unavailable:'Сайттан жіберу әзірге қолжетімсіз. Төменде хат нобайын дайындап, оны пошта қолданбасы арқылы жіберіңіз.', invalid:'Белгіленген өрістерді тексеріңіз.', fieldError:'Осы өрістің мазмұны мен ұзындығын тексеріңіз.', consent:'Commodity Chain Ltd. осы деректерді өтінішіме жауап беру үшін пайдалануына келісемін.', privacy:'Деректер өтінішіңізге жауап беру үшін пайдаланылады. Сайттан жіберу қосылғанда, хабарлама пошта қызметіне және info@commochain.ltd мекенжайына беріледі. Қосымшалар қабылданбайды. Құпия немесе сезімтал жеке мәліметтерді қоспаңыз. Деректеріңіз туралы сұрақтармен info@commochain.ltd мекенжайына жазыңыз.', fallbackPrivacy:'Нобай дайындау деректеріңізді осы сайтта жібермейді және сақтамайды. Хатты пошта қолданбасынан жіберу туралы шешімді өзіңіз қабылдайсыз.', emailFallback:'Пошта арқылы ыңғайлы ма?', retry:'Сол өтінішті қайта жіберу', newEnquiry:'Жаңа өтінішті бастау' },
};
