import type { Locale } from '../i18n';

// Certificate metadata and owner-confirmed governance facts. Sources: docs/public-claims.md.
// Dates are the dates shown on the supplied certificate, not an interpretation of its conditions.
export const companyFacts = {
  legalName: 'Commodity Chain Ltd.', bin: '250540900471', licence: 'AFSA-A-LA-2026-0014',
  institution: 'Authorised Market Institution', issued: '2026-06-18', expires: '2028-06-17',
  shareholder: 'Tech Hub Limited', equity: '10%', boardSeats: '1',
} as const;

export const publicSiteCopy = {
  en: {
    hero: 'Connecting real assets to capital.',
    intro: 'CommodityChain connects commodity assets with financing through investment-token, exchange and clearing infrastructure. Our initial focus is financing before harvest and grain in storage.',
    primary: 'Discuss your project', secondary: 'How it works', story: 'Explore the full story', closeStory: 'Return to the overview',
    stage: 'AFSA licensed. Controlled launch.',
    stageBody: 'Commodity Chain Ltd. holds an AFSA licence to operate an exchange and a clearing house for Investment Tokens, subject to applicable licence conditions. Technology review and approval of the first protocol are in progress.',
    permissions: 'Activities and participant access remain within current permissions and instrument-specific requirements. Holding the licence does not mean that every protocol or technology implementation has been approved.',
    licenceLabel: 'AFSA licence', stageLabel: 'Current operating stage', shareholderLabel: 'Strategic shareholder',
    shareholderShort: 'AIFC TechHub: 10% equity and one board seat.',
    shareholderBody: 'AIFC TechHub, legally Tech Hub Limited, holds a 10% equity stake and one seat on the Board of Directors. It is a strategic partner in developing tokenization infrastructure aligned with the AIFC ecosystem.',
    partnershipTitle: 'A strategic stake in the infrastructure.',
    partnershipNote: 'AIFC TechHub is not AFSA. Shareholding and board participation are not regulatory endorsement or a guarantee of investment performance or repayment.',
    applications: 'Two starting points. Different evidence.', applicationsIntro: 'Agriculture comes first. The evidence and financing structure depend on whether the harvest is still ahead or the grain is already in storage.',
    verification: 'From field evidence to a verifiable record.',
    verificationIntro: 'Financing starts with understanding the asset. Our agricultural verification workflow brings observations, business assessment and documented findings together, with publicly verifiable records on Solana.',
    evidence: [
      { title: 'Identify the field', body: 'Field identification and satellite imagery connect the assessment to the relevant location and agricultural land.' },
      { title: 'Understand the farmer', body: 'Historical and operational information supports farmer and business assessment. Scoring is an assessment input, not an official credit rating.' },
      { title: 'Observe the season', body: 'NDVI imagery indicates vegetation greenness and seasonal changes. It helps interpret crop development; it does not prove or guarantee a yield.' },
      { title: 'Document the findings', body: 'Periodic reports and supporting documents record observations and verification findings, including who supplied or assessed them.' },
      { title: 'Check the corresponding record', body: 'Publicly verifiable records on Solana provide a record layer alongside the underlying evidence. Checking a blockchain record does not independently establish that a physical observation is true.' },
    ],
    methodology: 'Company-described methodology. This is not a live dashboard or a report on a particular farm.',
    solanaTitle: 'Evidence, assessment and record are different things.',
    solanaBody: 'An observation or document, its supplier or assessor, and the corresponding blockchain record answer different questions. The record layer does not guarantee repayment, ownership, settlement or legal enforceability. Publicly accessible fields, storage arrangements and network details must be specified for each authorised example; no public example is presented here.',
    storageTitle: 'Grain in storage needs storage evidence.',
    storageBody: 'Satellite observations do not replace warehouse receipts, quantity and quality records, custody information or other evidence relevant to grain already in storage.',
    company: 'The company behind the infrastructure.', issued: 'Issue date shown', expires: 'Expiry date shown', institution: 'Institution status on the certificate',
    scope: 'Operating an Exchange and Operating a Clearing House for a facility for Investment Tokens, subject to applicable requirements and licence conditions.',
    certificateNote: 'The certificate refers to additional conditions. The metadata here does not reproduce or summarise those conditions.',
    participation: 'Start with the conversation relevant to you.',
    faq: 'Before we begin.', questions: [
      { title: 'Can I invest or trade through this website?', body: 'This is the public information and enquiry website, not a trading venue. Access to any instrument depends on current permissions, participant eligibility and its documents. You can discuss a project or potential participation with the team.' },
      { title: 'Does the licence approve every protocol?', body: 'No. The company holds its AFSA licence; technology review and approval of the first protocol are in progress. Licence permissions and specific protocol approvals are separate.' },
      { title: 'Does a token mean I own the grain or land?', body: 'Not automatically. Rights, obligations, redemption and payments follow the instrument’s documentation. Review those terms and the parties responsible for them.' },
      { title: 'Does verification remove investment risk?', body: 'No. Verification informs assessment; it does not guarantee harvest, repayment, returns or a secondary-market buyer. NDVI, business scoring and blockchain records each have limits.' },
      { title: 'What should I share in an initial enquiry?', body: 'A short description of your role, the asset and its location, and the question you want to discuss. Do not send confidential documents, personal farmer files or sensitive scoring inputs through this form.' },
    ],
    deeper: 'Explore the infrastructure in more detail.', future: 'Beyond the initial agricultural applications',
    futureNote: 'Music rights, gaming assets and water-facility projects are future directions, not currently available investment products.',
    transcript: 'Read the full story as text', heroImage: 'Cinematic illustration of agricultural land, not verification evidence.',
    verificationNav: 'Verification', faqNav: 'FAQ',
  },
  ru: {
    hero: 'Соединяем реальные активы с капиталом.',
    intro: 'CommodityChain связывает сырьевые активы с финансированием через инвестиционные токены, биржевую и клиринговую инфраструктуру. Начинаем с финансирования до сбора урожая и зерна на хранении.',
    primary: 'Обсудить ваш проект', secondary: 'Как это работает', story: 'Посмотреть полную историю', closeStory: 'Вернуться к обзору',
    stage: 'Лицензия AFSA. Поэтапный запуск.',
    stageBody: 'Commodity Chain Ltd. имеет лицензию AFSA на деятельность биржи и клиринговой палаты для Investment Tokens с соблюдением применимых лицензионных условий. Технологическая проверка и согласование первого протокола продолжаются.',
    permissions: 'Деятельность и доступ участников ограничены действующими разрешениями и требованиями конкретного инструмента. Наличие лицензии не означает одобрения каждого протокола или технологической реализации.',
    licenceLabel: 'Лицензия AFSA', stageLabel: 'Текущий этап работы', shareholderLabel: 'Стратегический акционер',
    shareholderShort: 'AIFC TechHub: 10% капитала и одно место в совете директоров.',
    shareholderBody: 'AIFC TechHub, юридическое наименование Tech Hub Limited, владеет 10% капитала и занимает одно место в совете директоров. Это стратегический партнёр по развитию инфраструктуры токенизации в экосистеме МФЦА.',
    partnershipTitle: 'Стратегическое участие в развитии инфраструктуры.',
    partnershipNote: 'AIFC TechHub — не AFSA. Участие в капитале и совете директоров не является одобрением регулятора и не гарантирует инвестиционные результаты или погашение.',
    applications: 'Две отправные точки. Разные подтверждения.', applicationsIntro: 'Начинаем с сельского хозяйства. Данные для проверки и структура финансирования зависят от того, предстоит ли урожай собрать или зерно уже находится на хранении.',
    verification: 'От данных о поле — к проверяемой записи.',
    verificationIntro: 'Финансирование начинается с понимания актива. Наша методология агропроверки объединяет наблюдения, оценку бизнеса и документированные выводы с публично проверяемыми записями в Solana.',
    evidence: [
      { title: 'Определить поле', body: 'Идентификация полей и спутниковые снимки связывают оценку с конкретным местоположением и сельскохозяйственными участками.' },
      { title: 'Изучить хозяйство', body: 'Исторические и операционные сведения помогают оценить фермера и его бизнес. Скоринг — один из факторов оценки, а не официальный кредитный рейтинг.' },
      { title: 'Наблюдать за сезоном', body: 'Снимки NDVI показывают состояние растительности и сезонные изменения. Они помогают оценивать развитие посевов, но не подтверждают и не гарантируют урожайность.' },
      { title: 'Зафиксировать выводы', body: 'Периодические отчёты и подтверждающие документы фиксируют наблюдения и результаты проверки, включая сведения о том, кто предоставил или оценил данные.' },
      { title: 'Проверить соответствующую запись', body: 'Публично проверяемые записи в Solana дополняют исходные данные. Проверка записи в блокчейне сама по себе не устанавливает достоверность наблюдения за физическим активом.' },
    ],
    methodology: 'Методология, описанная компанией. Это не работающая панель мониторинга и не отчёт о конкретном хозяйстве.',
    solanaTitle: 'Исходные данные, оценка и запись — не одно и то же.',
    solanaBody: 'Наблюдение или документ, его поставщик или проверяющий и соответствующая запись в блокчейне отвечают на разные вопросы. Запись не гарантирует погашение, право собственности, расчёты или юридическую исполнимость. Состав публичных данных, порядок хранения и сеть должны быть указаны для каждого разрешённого к публикации примера; на этой странице такой пример не представлен.',
    storageTitle: 'Зерну на хранении нужны данные о хранении.',
    storageBody: 'Спутниковые наблюдения не заменяют складские расписки, сведения о количестве и качестве, ответственном хранении и другие подтверждения для зерна, уже находящегося на складе.',
    company: 'Компания, которая создаёт инфраструктуру.', issued: 'Дата выдачи в сертификате', expires: 'Дата окончания в сертификате', institution: 'Статус учреждения в сертификате',
    scope: 'Operating an Exchange и Operating a Clearing House для площадки Investment Tokens с соблюдением применимых требований и лицензионных условий.',
    certificateNote: 'Сертификат содержит ссылку на дополнительные условия. Приведённые сведения не воспроизводят и не пересказывают эти условия.',
    participation: 'Начните с разговора о вашей задаче.',
    faq: 'Перед первым разговором.', questions: [
      { title: 'Можно ли инвестировать или торговать на этом сайте?', body: 'Это публичный информационный сайт для обращений, а не торговая площадка. Доступ к инструменту зависит от действующих разрешений, допуска участника и документов инструмента. С командой можно обсудить проект или возможное участие.' },
      { title: 'Означает ли лицензия одобрение каждого протокола?', body: 'Нет. Компания имеет лицензию AFSA; технологическая проверка и согласование первого протокола продолжаются. Лицензионные разрешения и одобрение конкретного протокола — разные вопросы.' },
      { title: 'Даёт ли токен право собственности на зерно или землю?', body: 'Не автоматически. Права, обязательства, погашение и выплаты определяются документами инструмента. Необходимо изучить эти условия и ответственность сторон.' },
      { title: 'Устраняет ли проверка инвестиционный риск?', body: 'Нет. Проверка помогает оценке, но не гарантирует урожай, погашение, доходность или покупателя на вторичном рынке. NDVI, скоринг бизнеса и блокчейн-записи имеют свои ограничения.' },
      { title: 'Что указать в первом обращении?', body: 'Кратко опишите свою роль, актив и его местонахождение, а также вопрос для обсуждения. Не отправляйте через эту форму конфиденциальные документы, персональные данные фермеров или чувствительные данные скоринга.' },
    ],
    deeper: 'Подробнее об устройстве инфраструктуры.', future: 'За пределами первых аграрных применений',
    futureNote: 'Музыкальные права, игровые активы и проекты водных объектов — направления развития, а не доступные сейчас инвестиционные продукты.',
    transcript: 'Прочитать полную историю', heroImage: 'Кинематографическая иллюстрация сельскохозяйственных земель, не данные проверки.',
    verificationNav: 'Проверка активов', faqNav: 'Вопросы',
  },
  kk: {
    hero: 'Нақты активтерді капиталмен байланыстырамыз.',
    intro: 'CommodityChain шикізат активтерін инвестициялық токендер, биржалық және клирингтік инфрақұрылым арқылы қаржыландырумен байланыстырады. Бастапқы бағытымыз — егін жинауға дейінгі қаржыландыру және сақтаудағы астық.',
    primary: 'Жобаңызды талқылау', secondary: 'Жұмыс тәртібі', story: 'Толық оқиғаны көру', closeStory: 'Шолуға оралу',
    stage: 'AFSA лицензиясы бар. Кезең-кезеңімен іске қосу.',
    stageBody: 'Commodity Chain Ltd. тиісті лицензиялық шарттарды сақтай отырып, Investment Tokens үшін биржа және клиринг палатасы қызметін жүргізуге AFSA лицензиясын иеленеді. Технологиялық тексеру және алғашқы хаттаманы келісу жалғасуда.',
    permissions: 'Қызмет пен қатысушылардың қолжетімділігі қолданыстағы рұқсаттармен және нақты құралдың талаптарымен шектеледі. Лицензияның болуы әр хаттаманың немесе технологиялық іске асырудың мақұлданғанын білдірмейді.',
    licenceLabel: 'AFSA лицензиясы', stageLabel: 'Қазіргі жұмыс кезеңі', shareholderLabel: 'Стратегиялық акционер',
    shareholderShort: 'AIFC TechHub: капиталдың 10%-ы және директорлар кеңесіндегі бір орын.',
    shareholderBody: 'AIFC TechHub, заңды атауы Tech Hub Limited, капиталдың 10%-ын иеленеді және директорлар кеңесінде бір орынға ие. Ол АХҚО экожүйесіне сәйкес токенизация инфрақұрылымын дамытудағы стратегиялық серіктес.',
    partnershipTitle: 'Инфрақұрылымды дамытуға стратегиялық қатысу.',
    partnershipNote: 'AIFC TechHub — AFSA емес. Капиталға және директорлар кеңесіне қатысу реттеушінің мақұлдауын, инвестициялық нәтижелерді немесе өтеуді кепілдендірмейді.',
    applications: 'Екі бастапқы нүкте. Әртүрлі дәлелдер.', applicationsIntro: 'Алдымен — ауыл шаруашылығы. Тексеру деректері мен қаржыландыру құрылымы егіннің әлі жиналмағанына немесе астықтың сақтауда тұрғанына байланысты.',
    verification: 'Егістік деректерінен тексерілетін жазбаға дейін.',
    verificationIntro: 'Қаржыландыру активті түсінуден басталады. Агротексеру әдістемеміз бақылауларды, бизнесті бағалауды және құжатталған қорытындыларды Solana желісіндегі ашық тексерілетін жазбалармен байланыстырады.',
    evidence: [
      { title: 'Егістікті анықтау', body: 'Егістікті сәйкестендіру және спутниктік суреттер бағалауды нақты орналасқан жермен және ауыл шаруашылығы алқаптарымен байланыстырады.' },
      { title: 'Шаруашылықты зерделеу', body: 'Тарихи және операциялық мәліметтер фермер мен бизнесті бағалауға көмектеседі. Скоринг — бағалау факторларының бірі, ресми кредиттік рейтинг емес.' },
      { title: 'Маусымды бақылау', body: 'NDVI суреттері өсімдік жамылғысының жасылдық деңгейі мен маусымдық өзгерістерін көрсетеді. Олар егістің дамуын түсіндіруге көмектеседі, бірақ өнімділікті растамайды және кепілдендірмейді.' },
      { title: 'Қорытындыларды құжаттау', body: 'Мерзімді есептер мен растайтын құжаттар бақылауларды, тексеру нәтижелерін және деректерді кім ұсынғанын немесе бағалағанын тіркейді.' },
      { title: 'Тиісті жазбаны тексеру', body: 'Solana желісіндегі ашық тексерілетін жазбалар бастапқы деректерді толықтырады. Блокчейн жазбасын тексеру физикалық актив туралы бақылаудың шындығын өздігінен дәлелдемейді.' },
    ],
    methodology: 'Компания сипаттаған әдістеме. Бұл жұмыс істеп тұрған бақылау панелі немесе нақты шаруашылық туралы есеп емес.',
    solanaTitle: 'Дерек, бағалау және жазба — әртүрлі ұғымдар.',
    solanaBody: 'Бақылау не құжат, оны ұсынушы немесе бағалаушы және тиісті блокчейн жазбасы әртүрлі сұрақтарға жауап береді. Жазба өтеуді, меншік құқығын, есеп айырысуды немесе заңдық орындалуды кепілдендірмейді. Ашық деректер құрамы, сақтау тәртібі мен желі жариялауға рұқсат етілген әр мысал үшін көрсетілуі тиіс; бұл бетте мұндай мысал берілмеген.',
    storageTitle: 'Сақтаудағы астыққа сақтау деректері қажет.',
    storageBody: 'Спутниктік бақылаулар қойма қолхаттарын, мөлшер мен сапа жазбаларын, жауапты сақтау мәліметтерін және қоймадағы астыққа қатысты басқа дәлелдерді алмастырмайды.',
    company: 'Инфрақұрылымды дамытатын компания.', issued: 'Сертификаттағы берілген күн', expires: 'Сертификаттағы аяқталу күні', institution: 'Сертификаттағы мекеме мәртебесі',
    scope: 'Investment Tokens алаңы үшін Operating an Exchange және Operating a Clearing House қызметтері, тиісті талаптар мен лицензиялық шарттарды сақтай отырып.',
    certificateNote: 'Сертификат қосымша шарттарға сілтеме жасайды. Мұндағы мәліметтер сол шарттарды қайталамайды және түсіндірмейді.',
    participation: 'Өз міндетіңізге сай әңгімеден бастаңыз.',
    faq: 'Алғашқы әңгімеге дейін.', questions: [
      { title: 'Осы сайт арқылы инвестициялауға немесе сауда жасауға бола ма?', body: 'Бұл — ақпарат пен өтініштерге арналған ашық сайт, сауда алаңы емес. Құралға қолжетімділік қолданыстағы рұқсаттарға, қатысушының жарамдылығына және құрал құжаттарына байланысты. Командамен жобаны немесе ықтимал қатысуды талқылауға болады.' },
      { title: 'Лицензия әр хаттаманың мақұлданғанын білдіре ме?', body: 'Жоқ. Компания AFSA лицензиясын иеленеді; технологиялық тексеру және алғашқы хаттаманы келісу жалғасуда. Лицензиялық рұқсаттар мен нақты хаттаманы мақұлдау — бөлек мәселелер.' },
      { title: 'Токен астыққа немесе жерге меншік құқығын бере ме?', body: 'Автоматты түрде бермейді. Құқықтар, міндеттемелер, өтеу және төлемдер құралдың құжаттарымен айқындалады. Осы шарттар мен тараптардың жауапкершілігін зерделеу қажет.' },
      { title: 'Тексеру инвестициялық тәуекелді жоя ма?', body: 'Жоқ. Тексеру бағалауға көмектеседі, бірақ өнімді, өтеуді, кірісті немесе қайталама нарықтағы сатып алушыны кепілдендірмейді. NDVI, бизнес скорингі және блокчейн жазбаларының шектеулері бар.' },
      { title: 'Алғашқы өтініште не көрсету керек?', body: 'Рөліңізді, активті және оның орналасқан жерін, талқылағыңыз келетін мәселені қысқаша сипаттаңыз. Осы нысан арқылы құпия құжаттарды, фермерлердің жеке деректерін немесе сезімтал скоринг мәліметтерін жібермеңіз.' },
    ],
    deeper: 'Инфрақұрылым құрылымы туралы толығырақ.', future: 'Алғашқы аграрлық қолданудан кейінгі бағыттар',
    futureNote: 'Музыкалық құқықтар, ойын активтері және су нысандары жобалары — даму бағыттары, қазір қолжетімді инвестициялық өнімдер емес.',
    transcript: 'Толық оқиғаны мәтін түрінде оқу', heroImage: 'Ауыл шаруашылығы жерлерінің кинематографиялық иллюстрациясы, тексеру деректері емес.',
    verificationNav: 'Активті тексеру', faqNav: 'Сұрақтар',
  },
} satisfies Record<Locale, object>;
