import type { Locale } from '../i18n';

// Certificate metadata and owner-confirmed governance facts. Sources: docs/public-claims.md.
// Dates are the dates shown on the supplied certificate, not an interpretation of its conditions.
export const companyFacts = {
  legalName: 'Commodity Chain Ltd.', bin: '250540900471', licence: 'AFSA-A-LA-2026-0014',
  institution: 'Authorised Market Institution', issued: '2026-06-18', expires: '2028-06-17',
  shareholder: 'Tech Hub Limited', equity: '10%', boardSeats: '1',
} as const;

export const publicSiteCopy = {
  en: {
    hero: 'Connecting real assets to capital.',
    intro: 'CommodityChain connects commodity assets with financing through investment-token, exchange and clearing infrastructure. Our initial focus is financing before harvest and grain in storage.',
    primary: 'Discuss your project', secondary: 'How it works', story: 'Explore the full story', closeStory: 'Return to the overview',
    stage: 'AFSA licensed. Controlled launch.',
    stageBody: 'Commodity Chain Ltd. holds an AFSA licence to operate an exchange and a clearing house for Investment Tokens, subject to applicable licence conditions. Technology review and approval of the first protocol are in progress.',
    permissions: 'Activities and participant access remain within current permissions and instrument-specific requirements. Holding the licence does not mean that every protocol or technology implementation has been approved.',
    licenceLabel: 'AFSA licence', stageLabel: 'Current operating stage', shareholderLabel: 'Strategic shareholder',
    shareholderShort: 'AIFC TechHub: 10% equity and one board seat.',
    shareholderBody: 'AIFC TechHub, legally Tech Hub Limited, holds a 10% equity stake and one seat on the Board of Directors. It is a strategic partner in developing tokenization infrastructure aligned with the AIFC ecosystem.',
    partnershipTitle: 'A strategic stake in the infrastructure.',
    partnershipNote: 'AIFC TechHub is not AFSA. Shareholding and board participation are not regulatory endorsement or a guarantee of investment performance or repayment.',
    applications: 'Two starting points. Different evidence.', applicationsIntro: 'Agriculture comes first. The evidence and financing structure depend on whether the harvest is still ahead or the grain is already in storage.',
    verification: 'From field evidence to a verifiable record.',
    verificationIntro: 'Financing starts with understanding the asset. Our agricultural verification workflow brings observations, business assessment and documented findings together, with publicly verifiable records on Solana.',
    evidence: [
      { title: 'Identify the field', body: 'Field identification and satellite imagery connect the assessment to the relevant location and agricultural land.' },
      { title: 'Understand the farmer', body: 'Historical and operational information supports farmer and business assessment. Scoring is an assessment input, not an official credit rating.' },
      { title: 'Observe the season', body: 'NDVI imagery indicates vegetation greenness and seasonal changes. It helps interpret crop development; it does not prove or guarantee a yield.' },
      { title: 'Document the findings', body: 'Periodic reports and supporting documents record observations and verification findings, including who supplied or assessed them.' },
      { title: 'Check the corresponding record', body: 'Publicly verifiable records on Solana provide a record layer alongside the underlying evidence. Checking a blockchain record does not independently establish that a physical observation is true.' },
    ],
    methodology: 'Company-described methodology. This is not a live dashboard or a report on a particular farm.',
    solanaTitle: 'Evidence, assessment and record are different things.',
    solanaBody: 'An observation or document, its supplier or assessor, and the corresponding blockchain record answer different questions. The record layer does not guarantee repayment, ownership, settlement or legal enforceability. Publicly accessible fields, storage arrangements and network details must be specified for each authorised example; no public example is presented here.',
    storageTitle: 'Inside the elevator: quantity and quality.',
    storageSummary: 'Grain in storage is checked using cameras, scales, laboratory testing and robots inside silos, alongside warehouse receipts and storage records.',
    storageBody: 'Stored-grain verification at the elevator uses smart sensing and measurement systems: cameras, scales, laboratory testing and robots inside silos. Together they provide measurements and observations of the quantity and quality of grain in storage.',
    storageDocuments: 'These measurements complement warehouse receipts, grain identification and custody records. Satellite observations of fields do not replace checks of grain inside the elevator.',
    company: 'The company behind the infrastructure.', issued: 'Issue date shown', expires: 'Expiry date shown', institution: 'Institution status on the certificate',
    scope: 'Operating an Exchange and Operating a Clearing House for a facility for Investment Tokens, subject to applicable requirements and licence conditions.',
    certificateNote: 'The certificate refers to additional conditions. The metadata here does not reproduce or summarise those conditions.',
    participation: 'Start with the conversation relevant to you.',
    faq: 'Before we begin.', questions: [
      { title: 'Can I invest or trade through this website?', body: 'This is the public information and enquiry website, not a trading venue. Access to any instrument depends on current permissions, participant eligibility and its documents. You can discuss a project or potential participation with the team.' },
      { title: 'Does the licence approve every protocol?', body: 'No. The company holds its AFSA licence; technology review and approval of the first protocol are in progress. Licence permissions and specific protocol approvals are separate.' },
      { title: 'Does a token mean I own the grain or land?', body: 'Not automatically. Rights, obligations, redemption and payments follow the instrument’s documentation. Review those terms and the parties responsible for them.' },
      { title: 'Does verification remove investment risk?', body: 'No. Verification informs assessment; it does not guarantee harvest, repayment, returns or a secondary-market buyer. NDVI, business scoring and blockchain records each have limits.' },
      { title: 'What should I share in an initial enquiry?', body: 'A short description of your role, the asset and its location, and the question you want to discuss. Do not send confidential documents, personal farmer files or sensitive scoring inputs through this form.' },
    ],
    deeper: 'Explore the infrastructure in more detail.', future: 'Beyond the initial agricultural applications',
    futureNote: 'Music rights, gaming assets and water-facility projects are future directions, not currently available investment products.',
    transcript: 'Read the full story as text', heroImage: 'Cinematic illustration of agricultural land, not verification evidence.',
    verificationNav: 'Verification', faqNav: 'FAQ',
  },
  zh: {
    hero: '连接实体资产与资本。',
    intro: 'CommodityChain 通过投资代币、交易所及清算基础设施，将大宗商品资产与融资连接起来。我们的初期重点是收获前融资和仓储粮食。',
    primary: '洽谈您的项目', secondary: '运作方式', story: '探索完整故事', closeStory: '返回概览',
    stage: '已获 AFSA 许可，受控启动。',
    stageBody: 'Commodity Chain Ltd. 持有 AFSA 颁发的许可证，可在遵守适用许可条件的前提下，为投资代币（Investment Tokens）运营交易所及清算所。目前，技术审查与首个协议的审批仍在进行中。',
    permissions: '业务活动及参与者准入须遵守现有许可范围和具体工具的要求。持有许可证并不意味着每个协议或技术实现均已获批。',
    licenceLabel: 'AFSA 许可证', stageLabel: '当前运营阶段', shareholderLabel: '战略股东',
    shareholderShort: 'AIFC TechHub：持股 10%，拥有一个董事会席位。',
    shareholderBody: 'AIFC TechHub 的法定名称为 Tech Hub Limited，持有公司 10% 的股权，并拥有一个董事会席位。作为战略合作伙伴，其参与建设与阿斯塔纳国际金融中心（AIFC）生态相协调的代币化基础设施。',
    partnershipTitle: '以战略持股参与基础设施建设。',
    partnershipNote: 'AIFC TechHub 并非 AFSA。持股及董事会参与不构成监管机构的认可，也不保证投资表现或偿付。',
    applications: '两种起点，不同的核验依据。', applicationsIntro: '我们从农业起步。核验依据与融资结构取决于粮食尚待收获，还是已经入库储存。',
    verification: '从田间证据到可核查记录。',
    verificationIntro: '融资始于对资产的了解。我们的农业核验流程将观测、经营评估及书面结论汇集起来，并在 Solana 上建立可公开核查的记录。',
    evidence: [
      { title: '识别地块', body: '地块识别与卫星影像将评估对应到具体地点和农业用地。' },
      { title: '了解农户', body: '历史资料和运营信息为农户及其经营状况的评估提供依据。评分是评估的参考因素，并非正式信用评级。' },
      { title: '跟踪生长季', body: 'NDVI 影像反映植被绿度及季节变化，有助于分析作物生长状况，但不能证明或保证产量。' },
      { title: '记录核验结果', body: '定期报告和支持文件记录观测及核验结果，并注明数据的提供方或评估方。' },
      { title: '核查对应记录', body: 'Solana 上可公开核查的记录为原始证据提供配套记录层。核查区块链记录本身，无法独立证实实物观测的真实性。' },
    ],
    methodology: '本页介绍公司所述的方法，并非实时数据看板或特定农场的报告。',
    solanaTitle: '证据、评估与记录各有作用。',
    solanaBody: '观测或文件、其提供方或评估方，以及对应的区块链记录，分别回答不同的问题。记录层不保证偿付、所有权、结算或法律上的可执行性。对于每个获准展示的示例，均须说明可公开访问的数据字段、存储安排及网络详情；本页暂未展示任何公开示例。',
    storageTitle: '粮仓内部：数量与质量。',
    storageSummary: '仓储粮食通过摄像头、称重设备、实验室检测及筒仓内机器人进行核验，并结合仓单和仓储记录。',
    storageBody: '粮食仓储设施内的核验采用智能感知与测量系统，包括摄像头、称重设备、实验室检测及筒仓内机器人。这些系统共同提供对库存粮食数量和质量的测量与观测。',
    storageDocuments: '这些测量结果补充仓单、粮食识别及保管记录。田间卫星观测不能替代对粮仓内粮食的检查。',
    company: '基础设施背后的公司。', issued: '证书所列签发日期', expires: '证书所列到期日期', institution: '证书所列机构身份',
    scope: '在遵守适用要求及许可条件的前提下，为投资代币（Investment Tokens）设施运营交易所（Operating an Exchange）及清算所（Operating a Clearing House）。',
    certificateNote: '证书提及附加条件。此处所列证书信息并未重现或概述这些条件。',
    participation: '从与您相关的话题开始。',
    faq: '开始之前，您可能想了解。', questions: [
      { title: '我可以通过本网站投资或交易吗？', body: '本网站用于公开信息展示和咨询，并非交易场所。任何工具的准入均取决于现有许可、参与者资格及其文件要求。您可以与团队洽谈项目或潜在参与机会。' },
      { title: '许可证是否代表所有协议均已获批？', body: '并非如此。公司已持有 AFSA 许可证，但技术审查及首个协议的审批仍在进行。许可证授权范围与具体协议审批是不同事项。' },
      { title: '持有代币是否意味着拥有粮食或土地？', body: '并不自动意味着拥有。权利、义务、赎回及支付安排以工具文件为准。请查阅相关条款及承担责任的各方。' },
      { title: '核验能否消除投资风险？', body: '不能。核验为评估提供依据，但不保证收成、偿付、回报或二级市场买方的存在。NDVI、经营评分和区块链记录各有局限。' },
      { title: '首次咨询需要提供哪些信息？', body: '请简要介绍您的角色、资产及其所在地，以及希望讨论的问题。请勿通过此表单发送保密文件、农户个人档案或敏感评分数据。' },
    ],
    deeper: '进一步了解基础设施。', future: '初期农业应用之外的探索',
    futureNote: '音乐权利、游戏资产及水生产设施项目是未来探索方向，并非当前可投资的产品。',
    transcript: '阅读完整故事文字版', heroImage: '农业用地的影片概念插图，并非核验证据。',
    verificationNav: '资产核验', faqNav: '常见问题',
  },
  ru: {
    hero: 'Соединяем реальные активы с капиталом.',
    intro: 'CommodityChain связывает сырьевые активы с финансированием через инвестиционные токены, биржевую и клиринговую инфраструктуру. Начинаем с финансирования до сбора урожая и зерна на хранении.',
    primary: 'Обсудить ваш проект', secondary: 'Как это работает', story: 'Посмотреть полную историю', closeStory: 'Вернуться к обзору',
    stage: 'Лицензия AFSA. Поэтапный запуск.',
    stageBody: 'Commodity Chain Ltd. имеет лицензию AFSA на деятельность биржи и клиринговой палаты для Investment Tokens с соблюдением применимых лицензионных условий. Технологическая проверка и согласование первого протокола продолжаются.',
    permissions: 'Деятельность и доступ участников ограничены действующими разрешениями и требованиями конкретного инструмента. Наличие лицензии не означает одобрения каждого протокола или технологической реализации.',
    licenceLabel: 'Лицензия AFSA', stageLabel: 'Текущий этап работы', shareholderLabel: 'Стратегический акционер',
    shareholderShort: 'AIFC TechHub: 10% капитала и одно место в совете директоров.',
    shareholderBody: 'AIFC TechHub, юридическое наименование Tech Hub Limited, владеет 10% капитала и занимает одно место в совете директоров. Это стратегический партнёр по развитию инфраструктуры токенизации в экосистеме МФЦА.',
    partnershipTitle: 'Стратегическое участие в развитии инфраструктуры.',
    partnershipNote: 'AIFC TechHub — не AFSA. Участие в капитале и совете директоров не является одобрением регулятора и не гарантирует инвестиционные результаты или погашение.',
    applications: 'Две отправные точки. Разные подтверждения.', applicationsIntro: 'Начинаем с сельского хозяйства. Данные для проверки и структура финансирования зависят от того, предстоит ли урожай собрать или зерно уже находится на хранении.',
    verification: 'От данных о поле — к проверяемой записи.',
    verificationIntro: 'Финансирование начинается с понимания актива. Наша методология агропроверки объединяет наблюдения, оценку бизнеса и документированные выводы с публично проверяемыми записями в Solana.',
    evidence: [
      { title: 'Определить поле', body: 'Идентификация полей и спутниковые снимки связывают оценку с конкретным местоположением и сельскохозяйственными участками.' },
      { title: 'Изучить хозяйство', body: 'Исторические и операционные сведения помогают оценить фермера и его бизнес. Скоринг — один из факторов оценки, а не официальный кредитный рейтинг.' },
      { title: 'Наблюдать за сезоном', body: 'Снимки NDVI показывают состояние растительности и сезонные изменения. Они помогают оценивать развитие посевов, но не подтверждают и не гарантируют урожайность.' },
      { title: 'Зафиксировать выводы', body: 'Периодические отчёты и подтверждающие документы фиксируют наблюдения и результаты проверки, включая сведения о том, кто предоставил или оценил данные.' },
      { title: 'Проверить соответствующую запись', body: 'Публично проверяемые записи в Solana дополняют исходные данные. Проверка записи в блокчейне сама по себе не устанавливает достоверность наблюдения за физическим активом.' },
    ],
    methodology: 'Методология, описанная компанией. Это не работающая панель мониторинга и не отчёт о конкретном хозяйстве.',
    solanaTitle: 'Исходные данные, оценка и запись — не одно и то же.',
    solanaBody: 'Наблюдение или документ, его поставщик или проверяющий и соответствующая запись в блокчейне отвечают на разные вопросы. Запись не гарантирует погашение, право собственности, расчёты или юридическую исполнимость. Состав публичных данных, порядок хранения и сеть должны быть указаны для каждого разрешённого к публикации примера; на этой странице такой пример не представлен.',
    storageTitle: 'На элеваторе: количество и качество.',
    storageSummary: 'Зерно на хранении проверяется с помощью камер, весов, лаборатории и роботов в силосах — вместе со складскими расписками и данными хранения.',
    storageBody: 'Верификация зерна на элеваторе опирается на умные датчики и измерительные системы: камеры, весы, лабораторные исследования и роботов внутри силосов. Вместе они дают измерения и наблюдения за количественными и качественными показателями зерна на хранении.',
    storageDocuments: 'Эти измерения дополняют складские расписки, идентификацию зерна и сведения об ответственном хранении. Спутниковые наблюдения за полями не заменяют проверку зерна внутри элеватора.',
    company: 'Компания, которая создаёт инфраструктуру.', issued: 'Дата выдачи в сертификате', expires: 'Дата окончания в сертификате', institution: 'Статус учреждения в сертификате',
    scope: 'Operating an Exchange и Operating a Clearing House для площадки Investment Tokens с соблюдением применимых требований и лицензионных условий.',
    certificateNote: 'Сертификат содержит ссылку на дополнительные условия. Приведённые сведения не воспроизводят и не пересказывают эти условия.',
    participation: 'Начните с разговора о вашей задаче.',
    faq: 'Перед первым разговором.', questions: [
      { title: 'Можно ли инвестировать или торговать на этом сайте?', body: 'Это публичный информационный сайт для обращений, а не торговая площадка. Доступ к инструменту зависит от действующих разрешений, допуска участника и документов инструмента. С командой можно обсудить проект или возможное участие.' },
      { title: 'Означает ли лицензия одобрение каждого протокола?', body: 'Нет. Компания имеет лицензию AFSA; технологическая проверка и согласование первого протокола продолжаются. Лицензионные разрешения и одобрение конкретного протокола — разные вопросы.' },
      { title: 'Даёт ли токен право собственности на зерно или землю?', body: 'Не автоматически. Права, обязательства, погашение и выплаты определяются документами инструмента. Необходимо изучить эти условия и ответственность сторон.' },
      { title: 'Устраняет ли проверка инвестиционный риск?', body: 'Нет. Проверка помогает оценке, но не гарантирует урожай, погашение, доходность или покупателя на вторичном рынке. NDVI, скоринг бизнеса и блокчейн-записи имеют свои ограничения.' },
      { title: 'Что указать в первом обращении?', body: 'Кратко опишите свою роль, актив и его местонахождение, а также вопрос для обсуждения. Не отправляйте через эту форму конфиденциальные документы, персональные данные фермеров или чувствительные данные скоринга.' },
    ],
    deeper: 'Подробнее об устройстве инфраструктуры.', future: 'За пределами первых аграрных применений',
    futureNote: 'Музыкальные права, игровые активы и проекты водных объектов — направления развития, а не доступные сейчас инвестиционные продукты.',
    transcript: 'Прочитать полную историю', heroImage: 'Кинематографическая иллюстрация сельскохозяйственных земель, не данные проверки.',
    verificationNav: 'Проверка активов', faqNav: 'Вопросы',
  },
  kk: {
    hero: 'Нақты активтерді капиталмен байланыстырамыз.',
    intro: 'CommodityChain шикізат активтерін инвестициялық токендер, биржалық және клирингтік инфрақұрылым арқылы қаржыландырумен байланыстырады. Бастапқы бағытымыз — егін жинауға дейінгі қаржыландыру және сақтаудағы астық.',
    primary: 'Жобаңызды талқылау', secondary: 'Жұмыс тәртібі', story: 'Толық оқиғаны көру', closeStory: 'Шолуға оралу',
    stage: 'AFSA лицензиясы бар. Кезең-кезеңімен іске қосу.',
    stageBody: 'Commodity Chain Ltd. тиісті лицензиялық шарттарды сақтай отырып, Investment Tokens үшін биржа және клиринг палатасы қызметін жүргізуге AFSA лицензиясын иеленеді. Технологиялық тексеру және алғашқы хаттаманы келісу жалғасуда.',
    permissions: 'Қызмет пен қатысушылардың қолжетімділігі қолданыстағы рұқсаттармен және нақты құралдың талаптарымен шектеледі. Лицензияның болуы әр хаттаманың немесе технологиялық іске асырудың мақұлданғанын білдірмейді.',
    licenceLabel: 'AFSA лицензиясы', stageLabel: 'Қазіргі жұмыс кезеңі', shareholderLabel: 'Стратегиялық акционер',
    shareholderShort: 'AIFC TechHub: капиталдың 10%-ы және директорлар кеңесіндегі бір орын.',
    shareholderBody: 'AIFC TechHub, заңды атауы Tech Hub Limited, капиталдың 10%-ын иеленеді және директорлар кеңесінде бір орынға ие. Ол АХҚО экожүйесіне сәйкес токенизация инфрақұрылымын дамытудағы стратегиялық серіктес.',
    partnershipTitle: 'Инфрақұрылымды дамытуға стратегиялық қатысу.',
    partnershipNote: 'AIFC TechHub — AFSA емес. Капиталға және директорлар кеңесіне қатысу реттеушінің мақұлдауын, инвестициялық нәтижелерді немесе өтеуді кепілдендірмейді.',
    applications: 'Екі бастапқы нүкте. Әртүрлі дәлелдер.', applicationsIntro: 'Алдымен — ауыл шаруашылығы. Тексеру деректері мен қаржыландыру құрылымы егіннің әлі жиналмағанына немесе астықтың сақтауда тұрғанына байланысты.',
    verification: 'Егістік деректерінен тексерілетін жазбаға дейін.',
    verificationIntro: 'Қаржыландыру активті түсінуден басталады. Агротексеру әдістемеміз бақылауларды, бизнесті бағалауды және құжатталған қорытындыларды Solana желісіндегі ашық тексерілетін жазбалармен байланыстырады.',
    evidence: [
      { title: 'Егістікті анықтау', body: 'Егістікті сәйкестендіру және спутниктік суреттер бағалауды нақты орналасқан жермен және ауыл шаруашылығы алқаптарымен байланыстырады.' },
      { title: 'Шаруашылықты зерделеу', body: 'Тарихи және операциялық мәліметтер фермер мен бизнесті бағалауға көмектеседі. Скоринг — бағалау факторларының бірі, ресми кредиттік рейтинг емес.' },
      { title: 'Маусымды бақылау', body: 'NDVI суреттері өсімдік жамылғысының жасылдық деңгейі мен маусымдық өзгерістерін көрсетеді. Олар егістің дамуын түсіндіруге көмектеседі, бірақ өнімділікті растамайды және кепілдендірмейді.' },
      { title: 'Қорытындыларды құжаттау', body: 'Мерзімді есептер мен растайтын құжаттар бақылауларды, тексеру нәтижелерін және деректерді кім ұсынғанын немесе бағалағанын тіркейді.' },
      { title: 'Тиісті жазбаны тексеру', body: 'Solana желісіндегі ашық тексерілетін жазбалар бастапқы деректерді толықтырады. Блокчейн жазбасын тексеру физикалық актив туралы бақылаудың шындығын өздігінен дәлелдемейді.' },
    ],
    methodology: 'Компания сипаттаған әдістеме. Бұл жұмыс істеп тұрған бақылау панелі немесе нақты шаруашылық туралы есеп емес.',
    solanaTitle: 'Дерек, бағалау және жазба — әртүрлі ұғымдар.',
    solanaBody: 'Бақылау не құжат, оны ұсынушы немесе бағалаушы және тиісті блокчейн жазбасы әртүрлі сұрақтарға жауап береді. Жазба өтеуді, меншік құқығын, есеп айырысуды немесе заңдық орындалуды кепілдендірмейді. Ашық деректер құрамы, сақтау тәртібі мен желі жариялауға рұқсат етілген әр мысал үшін көрсетілуі тиіс; бұл бетте мұндай мысал берілмеген.',
    storageTitle: 'Элеваторда: астықтың мөлшері мен сапасы.',
    storageSummary: 'Сақтаудағы астық камералар, таразылар, зертхана және силос ішіндегі роботтар арқылы, қойма қолхаттары мен сақтау деректерімен бірге тексеріледі.',
    storageBody: 'Элеватордағы астықты тексеру ақылды датчиктер мен өлшеу жүйелеріне сүйенеді: камералар, таразылар, зертханалық зерттеулер және силос ішіндегі роботтар. Олар бірге сақтаудағы астықтың сандық және сапалық көрсеткіштері бойынша өлшеулер мен бақылаулар береді.',
    storageDocuments: 'Бұл өлшеулер қойма қолхаттарын, астықты сәйкестендіру және жауапты сақтау деректерін толықтырады. Егістікті спутниктен бақылау элеватор ішіндегі астықты тексеруді алмастырмайды.',
    company: 'Инфрақұрылымды дамытатын компания.', issued: 'Сертификаттағы берілген күн', expires: 'Сертификаттағы аяқталу күні', institution: 'Сертификаттағы мекеме мәртебесі',
    scope: 'Investment Tokens алаңы үшін Operating an Exchange және Operating a Clearing House қызметтері, тиісті талаптар мен лицензиялық шарттарды сақтай отырып.',
    certificateNote: 'Сертификат қосымша шарттарға сілтеме жасайды. Мұндағы мәліметтер сол шарттарды қайталамайды және түсіндірмейді.',
    participation: 'Өз міндетіңізге сай әңгімеден бастаңыз.',
    faq: 'Алғашқы әңгімеге дейін.', questions: [
      { title: 'Осы сайт арқылы инвестициялауға немесе сауда жасауға бола ма?', body: 'Бұл — ақпарат пен өтініштерге арналған ашық сайт, сауда алаңы емес. Құралға қолжетімділік қолданыстағы рұқсаттарға, қатысушының жарамдылығына және құрал құжаттарына байланысты. Командамен жобаны немесе ықтимал қатысуды талқылауға болады.' },
      { title: 'Лицензия әр хаттаманың мақұлданғанын білдіре ме?', body: 'Жоқ. Компания AFSA лицензиясын иеленеді; технологиялық тексеру және алғашқы хаттаманы келісу жалғасуда. Лицензиялық рұқсаттар мен нақты хаттаманы мақұлдау — бөлек мәселелер.' },
      { title: 'Токен астыққа немесе жерге меншік құқығын бере ме?', body: 'Автоматты түрде бермейді. Құқықтар, міндеттемелер, өтеу және төлемдер құралдың құжаттарымен айқындалады. Осы шарттар мен тараптардың жауапкершілігін зерделеу қажет.' },
      { title: 'Тексеру инвестициялық тәуекелді жоя ма?', body: 'Жоқ. Тексеру бағалауға көмектеседі, бірақ өнімді, өтеуді, кірісті немесе қайталама нарықтағы сатып алушыны кепілдендірмейді. NDVI, бизнес скорингі және блокчейн жазбаларының шектеулері бар.' },
      { title: 'Алғашқы өтініште не көрсету керек?', body: 'Рөліңізді, активті және оның орналасқан жерін, талқылағыңыз келетін мәселені қысқаша сипаттаңыз. Осы нысан арқылы құпия құжаттарды, фермерлердің жеке деректерін немесе сезімтал скоринг мәліметтерін жібермеңіз.' },
    ],
    deeper: 'Инфрақұрылым құрылымы туралы толығырақ.', future: 'Алғашқы аграрлық қолданудан кейінгі бағыттар',
    futureNote: 'Музыкалық құқықтар, ойын активтері және су нысандары жобалары — даму бағыттары, қазір қолжетімді инвестициялық өнімдер емес.',
    transcript: 'Толық оқиғаны мәтін түрінде оқу', heroImage: 'Ауыл шаруашылығы жерлерінің кинематографиялық иллюстрациясы, тексеру деректері емес.',
    verificationNav: 'Активті тексеру', faqNav: 'Сұрақтар',
  },
} satisfies Record<Locale, object>;
